services:
  server:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    container_name: server-container
    ports:
      - '3000:3000/udp'
    volumes:
      - ../cmd/server:/app